-- Soul Board Schema for Supabase / PostgreSQL
-- 此檔案供日後升級至 Supabase 使用

-- Profiles table (optional, for authenticated users)
create table if not exists public.profiles (
  id uuid references auth.users on delete cascade primary key,
  display_name text,
  created_at timestamptz not null default now()
);

-- Posts table
create table if not exists public.posts (
  id bigint generated by default as identity primary key,
  author_id uuid references public.profiles(id) on delete set null,
  anon_id uuid not null,
  nickname text,
  topic text not null check (topic in ('love', 'work', 'random', 'tarot')),
  message text not null check (char_length(message) between 1 and 500),
  reactions int not null default 0,
  hot_score numeric not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Replies table
create table if not exists public.replies (
  id bigint generated by default as identity primary key,
  post_id bigint references public.posts(id) on delete cascade not null,
  author_id uuid references public.profiles(id) on delete set null,
  anon_id uuid not null,
  nickname text,
  message text not null check (char_length(message) between 1 and 400),
  created_at timestamptz not null default now()
);

-- Reactions table
create table if not exists public.reactions (
  id bigint generated by default as identity primary key,
  post_id bigint references public.posts(id) on delete cascade not null,
  user_key text not null,
  kind text not null default 'like' check (kind in ('like', 'sparkle')),
  created_at timestamptz not null default now(),
  constraint uq_reactions_post_user unique (post_id, user_key, kind)
);

-- Reports table
create table if not exists public.reports (
  id bigint generated by default as identity primary key,
  post_id bigint references public.posts(id) on delete cascade not null,
  reporter_key text not null,
  reason text not null,
  created_at timestamptz not null default now()
);

-- Indexes
create index if not exists idx_posts_created_at on public.posts(created_at desc);
create index if not exists idx_posts_topic_created_at on public.posts(topic, created_at desc);
create index if not exists idx_posts_hot_score_desc on public.posts(hot_score desc nulls last, created_at desc);
create index if not exists idx_replies_post_id_created_at on public.replies(post_id, created_at);

-- Enable Row Level Security (RLS)
alter table public.profiles enable row level security;
alter table public.posts enable row level security;
alter table public.replies enable row level security;
alter table public.reactions enable row level security;
alter table public.reports enable row level security;

-- RLS Policies - Read (public)
create policy "read_profiles" on public.profiles for select using (true);
create policy "read_posts" on public.posts for select using (true);
create policy "read_replies" on public.replies for select using (true);
create policy "read_reactions" on public.reactions for select using (true);

-- RLS Policies - Insert
create policy "insert_posts" on public.posts for insert
  with check ((auth.uid() is not null) or (anon_id is not null));

create policy "insert_replies" on public.replies for insert
  with check ((auth.uid() is not null) or (anon_id is not null));

create policy "insert_reactions" on public.reactions for insert
  with check ((auth.uid() is not null) or (user_key is not null));

create policy "insert_reports" on public.reports for insert
  with check ((auth.uid() is not null) or (reporter_key is not null));

-- RLS Policies - Update (author only)
create policy "update_my_post" on public.posts for update
  using (author_id = auth.uid());

create policy "update_my_reply" on public.replies for update
  using (author_id = auth.uid());

-- RLS Policies - Delete (author only)
create policy "delete_my_post" on public.posts for delete
  using (author_id = auth.uid());

create policy "delete_my_reply" on public.replies for delete
  using (author_id = auth.uid());

-- Functions for automatic updated_at
create or replace function public.handle_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

create trigger on_post_updated
  before update on public.posts
  for each row
  execute function public.handle_updated_at();
